- name: Project Manager Configuration
  hosts: group_sys
  become: yes
  vars:
    user: asgef
    project_name: gwent_website
    project_path: /home/{{ user }}/projects/{{ project_name }}

  tasks:
    # - name: Generate password using openssl
    #   command: "openssl rand -base64 12"
    #   register: random_password

    # - name: Create PostgreSQL user
    #   community.postgresql.postgresql_user:
    #     name: "{{ user }}"
    #     password: "{{ random_password.stdout }}"
    #     state: present
    #     login_user: postgres
    #     login_password: ""
    #     login_host: /var/run/postgresql  # Используем сокет для peer-аутентификации

    # - name: Create PostgreSQL db
    #   community.postgresql.postgresql_db:
    #     name: "{{ project_name }}"
    #     owner: "{{ user }}"
    #     state: present
    #     login_user: postgres
    #     login_password: ""
    #     login_host: /var/run/postgresql  # Используем сокет для peer-аутентификации
        


    # - name: Output database connection details
    #   debug:
    #     msg: |
    #       db_link: postgresql://{{ user }}:{{ random_password.stdout }}@{{ ansible_host }}/{{ project_name }}
    #       Database connection details:
    #       User: {{ user }}
    #       Database: {{ project_name }}
    #       Host: {{ ansibe_host }}
    #       Password: {{ random_password.stdout }}
    
    # - name: Set environment variable in local file
    #   local_action: # Таска выполняется на localhost
    #     module: lineinfile
    #     path: '{{ project_path }}/.env_prod'
    #     line: 'DATABASE_URL=postgresql://{{ user }}:{{ random_password.stdout }}@{{ ansible_host }}/{{ project_name }}'
    #     create: yes

    
    - name: Add GitHub in known_hosts
      ansible.builtin.shell: ssh-keyscan github.com >> ~/.ssh/known_hosts
