- hosts: all
  become: yes
  vars:
    user: asgef
    asdf_version: "v0.14.0"

  tasks:
    # Для последующей установки Python и Postgress потребуются пакеты

    - name: Install package for Python and psql
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - ssh
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - libffi-dev
        - libncursesw5-dev
        - libgdbm-dev
        - libnss3-dev
        - liblzma-dev
        - libyaml-dev
        - tk-dev
        - uuid-dev
        - python3-psycopg2
        - pipx
        - postgresql
        - make
        - unzip
        - fontconfig
        - mosh
        - zip

  # Установка asdf и плагинов

    - name: Check if .asdf directory exists
      stat:
        path: "/home/{{ user }}/.asdf"
      register: asdf_dir

    - name: Clone ASDF repository
      git:
        repo: 'https://github.com/asdf-vm/asdf.git'
        dest: "/home/{{ user }}/.asdf"
        version: "{{ asdf_version }}"
        update: no
      become_user: "{{ user }}"
      when: not asdf_dir.stat.exists

    - name: Add asdf to .bashrc
      lineinfile:
        path: "/home/{{ user }}/.bashrc"
        line: '. $HOME/.asdf/asdf.sh'
        create: yes
      become_user: "{{ user }}"

    - name: Ensure .bashrc changes are applied
      shell: source /home/{{ user }}/.bashrc
      become_user: "{{ user }}"
      args:
        executable: /bin/bash

    - block:

    # Python
        - name: Add Python plugin to asdf
          shell: asdf plugin-add python
          become_user: "{{ user }}"

        - name: Install latest Python version
          shell: asdf install python latest
          become_user: "{{ user }}"

        - name: Set latest Python version as global
          shell: asdf global python latest
          args:
            executable: /bin/bash
          become_user: "{{ user }}"

        - name: Set alias for Python
          ansible.builtin.command:
            cmd: echo alias py='python' >> /home/{{ user }}/.bashrc
          become_user: "{{ user }}"

    # Poetry
        - name: Add Poetry plugin to asdf
          shell: asdf plugin-add poetry https://github.com/asdf-community/asdf-poetry.git
          become_user: "{{ user }}"

        - name: Install latest Poetry version
          shell: asdf install poetry latest
          become_user: "{{ user }}"

        - name: Set latest Poetry version as global
          shell: asdf global poetry latest
          args:
            executable: /bin/bash
          become_user: "{{ user }}"

      environment:
        PATH: "/home/{{ user }}/.asdf/bin:/home/{{ user }}/.asdf/shims:{{ ansible_env.PATH }}"
    



    - name: Add PostgreSQL role
      community.postgresql.postgresql_user:
        name: "{{ user }}"
        role_attr_flags: "CREATEDB,CREATEROLE"
      become_user: postgres

    - name: Create PostgreSQL database
      community.postgresql.postgresql_db:
        name: test_1
      become_user: postgres

    - name: Grant privileges to role on database
      community.postgresql.postgresql_privs:
        database: test_1
        type: database
        privs: ALL
        objs: test_1
        roles: "{{ user }}"
      become_user: postgres
      