collections:
  # Install a collection from Ansible Galaxy "ansible-galaxy install -r requirements.yml"
  - name: osx_provisioner.collection
  - name: geerlingguy.mac
  - name: community.postgresql
  - name: community.general


roles:
  - name: viasite-ansible.zsh

