- name: Update system
#  gather_facts: No
  hosts: group_sys
  vars:

  tasks:
    - name: Ensure /var/lib/apt/lists directory exists
      ansible.builtin.file:
        path: /var/lib/apt/lists
        state: directory
        owner: root
        group: root
        mode: '755'
      become: yes

    - name: create block-list
      ansible.builtin.file:
        path: /var/lib/apt/lists/lock
        state: touch
        owner: root
        group: root
        mode: '640'
      become: yes

    - name: Update apt package index
      apt:
        update_cache: yes
      become: yes

    # Обновляем приложения
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      become: yes
    
    # Для обновления гита требуется его переустановка

    - name: Remove old GIT version
      apt:
        name: git
        state: absent
      become: yes
    
    - name: Add GIT PPA repository
      apt_repository:
        repo: ppa:git-core/ppa
        state: present
      become: yes

    - name: Install latest GIT version
      apt:
        name: git
      become: yes



    # Устанавливаем приложения
    
    